
--CLASSE
INSERT INTO `Classe` (`nomeClasse`) VALUES ("ante blandit viverra. Donec tempus"),("imperdiet dictum"),("vehicula risus. Nulla eget metus"),("diam"),("nunc interdum feugiat. Sed nec"),("erat. Vivamus nisi."),("Donec non justo. Proin"),("elementum"),("adipiscing elit. Etiam laoreet, libero"),("netus et");
INSERT INTO `Classe` (`nomeClasse`) VALUES ("nisi"),("Phasellus dolor"),("eu, ultrices sit amet,"),("vel, convallis in, cursus"),("est mauris, rhoncus id,"),("sit amet, faucibus"),("sagittis. Duis"),("ornare, lectus ante dictum mi,"),("urna et arcu imperdiet ullamcorper."),("Donec non");
INSERT INTO `Classe` (`nomeClasse`) VALUES ("Mauris vestibulum,"),("in molestie tortor nibh sit"),("vitae"),("sit amet,"),("massa. Quisque porttitor"),("amet, risus. Donec"),("et"),("ut nisi a"),("metus"),("egestas");
INSERT INTO `Classe` (`nomeClasse`) VALUES ("venenatis lacus. Etiam bibendum"),("tellus non magna. Nam"),("nisi. Cum sociis natoque penatibus"),("ac,"),("sollicitudin adipiscing ligula. Aenean gravida"),("commodo hendrerit. Donec"),("Pellentesque"),("Nulla eu"),("in aliquet lobortis, nisi"),("Sed");
INSERT INTO `Classe` (`nomeClasse`) VALUES ("magna, malesuada"),("Proin mi. Aliquam"),("Sed"),("Suspendisse aliquet, sem ut cursus"),("Aliquam vulputate ullamcorper"),("ornare, elit"),("vel pede blandit congue."),("luctus et ultrices posuere cubilia"),("dignissim. Maecenas ornare egestas"),("mattis velit justo nec ante.");
INSERT INTO `Classe` (`nomeClasse`) VALUES ("quis diam"),("Integer vulputate, risus"),("Morbi quis urna. Nunc quis"),("vehicula risus."),("ultricies ligula. Nullam enim."),("non,"),("posuere,"),("a nunc. In at pede."),("diam. Pellentesque habitant"),("Aenean");
INSERT INTO `Classe` (`nomeClasse`) VALUES ("luctus sit amet,"),("elit"),("purus sapien, gravida non, sollicitudin"),("ipsum"),("elementum"),("et ultrices posuere cubilia"),("vitae, erat."),("natoque penatibus et magnis dis"),("dolor dapibus gravida."),("egestas nunc");
INSERT INTO `Classe` (`nomeClasse`) VALUES ("non"),("arcu. Vestibulum ante"),("dictum sapien. Aenean massa. Integer"),("sapien. Cras"),("at pretium aliquet,"),("massa. Integer vitae nibh. Donec"),("eu tempor erat"),("nec tempus"),("nec ligula consectetuer rhoncus. Nullam"),("sed turpis nec");
INSERT INTO `Classe` (`nomeClasse`) VALUES ("Nulla eget metus eu erat"),("ipsum sodales purus, in"),("est, congue a, aliquet"),("ligula tortor,"),("ante. Nunc mauris"),("scelerisque dui. Suspendisse ac metus"),("turpis vitae purus gravida sagittis."),("feugiat. Sed nec metus"),("vestibulum"),("dolor elit, pellentesque");
INSERT INTO `Classe` (`nomeClasse`) VALUES ("magna. Sed eu eros."),("et netus et malesuada fames"),("Mauris vel turpis."),("Vivamus"),("eleifend"),("auctor"),("lobortis quam a felis"),("gravida nunc sed"),("arcu. Sed eu"),("Nunc mauris. Morbi");

--JOGADOR
INSERT INTO `Jogador` (`nome`,`email`,`idade`) VALUES ("Fritz","Utsagittislobortis@Suspendissedui.ca",52),("Gregory","libero.Integer.in@pharetraNamac.com",44),("Joel","eleifend@enimCurabitur.co.uk",56),("Dennis","Phasellus@erat.org",98),("Bevis","libero.mauris@urna.org",28),("Davis","sapien@faucibusleo.org",83),("Dorian","non.egestas.a@pede.com",33),("Malachi","sit.amet@Donecnon.org",6),("Kennedy","quis@velnisl.com",59),("Nash","vel.arcu.eu@eueleifendnec.ca",53);
INSERT INTO `Jogador` (`nome`,`email`,`idade`) VALUES ("Forrest","ridiculus.mus@ut.ca",86),("Ray","ante.Nunc.mauris@Proin.co.uk",69),("Kennan","at@dictumcursusNunc.ca",62),("Aidan","iaculis.enim@nequevitaesemper.edu",68),("Chester","ligula.tortor.dictum@Nunc.org",91),("Buckminster","ac.feugiat@morbitristiquesenectus.net",90),("Aladdin","dictum.Phasellus.in@erategettincidunt.edu",19),("Logan","nec.malesuada.ut@arcu.org",17),("Yasir","nec.quam.Curabitur@nuncrisus.com",50),("Hamish","vel.convallis@convallisconvallis.com",45);
INSERT INTO `Jogador` (`nome`,`email`,`idade`) VALUES ("Damian","diam@vel.org",37),("Theodore","Pellentesque.ut.ipsum@nonsollicitudin.com",48),("Colby","viverra.Donec@Class.org",31),("Gil","elit.erat@libero.com",62),("Chandler","elit.Aliquam.auctor@disparturient.co.uk",36),("Zane","felis@Nullafacilisi.com",25),("Ronan","Phasellus@idmagnaet.edu",94),("Harrison","mollis.non.cursus@pharetra.edu",52),("David","tristique.ac.eleifend@nisiMaurisnulla.co.uk",6),("Ahmed","vitae.purus@magnaDuisdignissim.com",82);
INSERT INTO `Jogador` (`nome`,`email`,`idade`) VALUES ("Alexander","conubia@Vivamuseuismod.co.uk",32),("Bernard","ligula@natoquepenatibuset.edu",78),("Hamish","a@dolornonummyac.ca",96),("Dorian","orci.consectetuer@posuereat.org",56),("Armand","erat.vel.pede@amet.edu",12),("Amery","lobortis@Nam.com",77),("Jared","accumsan.sed@blanditNam.org",62),("Avram","dui.lectus.rutrum@magnisdisparturient.ca",88),("Garth","vitae.orci@etmagnis.edu",63),("Allistair","commodo@nonluctus.com",49);
INSERT INTO `Jogador` (`nome`,`email`,`idade`) VALUES ("Uriel","felis.orci@SeddictumProin.org",85),("Xanthus","volutpat@sit.ca",21),("Barclay","Sed.neque@urna.net",52),("Colby","In@magna.com",55),("Ezra","risus@incursus.co.uk",4),("Roth","non.feugiat.nec@metusurnaconvallis.org",19),("Malik","enim.consequat@Integersemelit.com",78),("Tanek","et@non.net",69),("Tate","adipiscing.lacus@facilisisSuspendisse.edu",61),("Sebastian","sem.magna.nec@aarcu.com",87);
INSERT INTO `Jogador` (`nome`,`email`,`idade`) VALUES ("Dennis","mollis.vitae@duiSuspendisseac.edu",7),("Eagan","Phasellus@semsempererat.net",48),("Ryan","odio.vel@odio.co.uk",52),("Colin","magna.Suspendisse.tristique@et.edu",90),("Jordan","orci.luctus@sedsemegestas.net",30),("Gil","dolor.dolor@Pellentesquehabitantmorbi.net",16),("Gary","eu@Morbi.edu",11),("Patrick","dictum.Phasellus.in@Vestibulum.ca",62),("Hakeem","volutpat@nislMaecenasmalesuada.net",22),("Gary","ornare.sagittis@ridiculus.net",76);
INSERT INTO `Jogador` (`nome`,`email`,`idade`) VALUES ("Amal","aliquet.libero@luctus.co.uk",83),("Jerome","ante.lectus.convallis@Nullam.co.uk",34),("George","Suspendisse@NullafacilisiSed.net",56),("Wayne","neque.non.quam@aliquameuaccumsan.org",43),("Martin","et.magnis.dis@Integer.org",29),("Ahmed","eu.dui.Cum@lectusrutrum.co.uk",38),("Burton","magna@ultriciesornareelit.ca",60),("Beau","nisl@SedmolestieSed.ca",81),("Jacob","Praesent.eu.nulla@a.com",95),("Kennedy","sed.dolor.Fusce@massaQuisqueporttitor.org",27);
INSERT INTO `Jogador` (`nome`,`email`,`idade`) VALUES ("Christian","eget@erat.com",53),("Denton","ornare@senectusetnetus.edu",43),("Victor","ornare@SuspendisseeleifendCras.ca",99),("Wang","ac@iaculisaliquet.co.uk",19),("Bruno","bibendum.Donec@loremipsumsodales.co.uk",34),("Aristotle","scelerisque.neque.sed@Lorem.ca",70),("Lionel","urna.Nunc@semelit.net",31),("Giacomo","tellus.eu@dignissim.ca",35),("Timothy","Sed@magnaetipsum.net",35),("Dane","ante@enimEtiam.edu",63);
INSERT INTO `Jogador` (`nome`,`email`,`idade`) VALUES ("Clayton","Duis@Cras.org",65),("Driscoll","auctor.nunc@montesnasceturridiculus.com",64),("Derek","id@natoquepenatibus.org",42),("Randall","tincidunt.nibh.Phasellus@blanditenim.org",2),("Yoshio","et.magnis@congueelit.edu",21),("Connor","magna.nec@Nullam.org",25),("Byron","fames.ac@Praesent.co.uk",92),("Armando","vel.sapien.imperdiet@et.net",63),("Keaton","orci.Ut.sagittis@aaliquet.com",97),("Elliott","purus@luctuset.ca",40);
INSERT INTO `Jogador` (`nome`,`email`,`idade`) VALUES ("Hedley","eleifend@odio.ca",25),("Michael","arcu.Sed@rhoncusid.edu",28),("Clark","rutrum.eu.ultrices@sitametconsectetuer.co.uk",75),("Ahmed","Ut.nec@odiosempercursus.net",44),("Ira","Duis.a@ligula.org",53),("Brody","et.nunc.Quisque@lorem.com",13),("Barrett","parturient@interdumCurabiturdictum.ca",40),("Lane","interdum.enim@Donecfelis.org",94),("Drew","egestas.Fusce@volutpat.com",43),("Ulric","magnis@magnaatortor.co.uk",58);

--ATAQUE
INSERT INTO `Ataque` (`nome`,`dano`) VALUES ("Dennis",75),("Amela",46),("Farrah",50),("Jackson",68),("Abraham",16),("Delilah",35),("Skyler",59),("Barclay",41),("Shana",62),("Dorian",82);
INSERT INTO `Ataque` (`nome`,`dano`) VALUES ("Oleg",30),("Shoshana",36),("Rashad",87),("Akeem",44),("Carol",31),("Gwendolyn",69),("Paki",29),("Noelle",51),("Garrison",80),("Raven",33);
INSERT INTO `Ataque` (`nome`,`dano`) VALUES ("Breanna",58),("Kristen",52),("Alea",98),("Kane",64),("Halee",2),("Cullen",2),("Whilemina",21),("Lareina",38),("Sawyer",48),("Uma",37);
INSERT INTO `Ataque` (`nome`,`dano`) VALUES ("Sloane",85),("Charles",48),("Gary",24),("Jasper",31),("Sopoline",25),("Amy",44),("Jameson",93),("Kasimir",23),("Tiger",39),("Ralph",74);
INSERT INTO `Ataque` (`nome`,`dano`) VALUES ("Nathan",26),("Maya",38),("Kuame",11),("Nelle",23),("Flavia",96),("Hayden",92),("Rhiannon",3),("Jenna",46),("Shellie",78),("Nehru",81);
INSERT INTO `Ataque` (`nome`,`dano`) VALUES ("Brenda",42),("Isabella",34),("Ira",13),("Fleur",93),("Ina",38),("Avram",63),("Steven",8),("Hermione",48),("Mark",89),("Azalia",25);
INSERT INTO `Ataque` (`nome`,`dano`) VALUES ("Savannah",82),("Uriah",4),("Sigourney",78),("Edan",64),("Harriet",97),("Vaughan",67),("Shellie",100),("Ciara",45),("Giselle",96),("Morgan",49);
INSERT INTO `Ataque` (`nome`,`dano`) VALUES ("Erin",48),("Chelsea",24),("Adrian",36),("Keefe",67),("Quamar",30),("Wesley",66),("Heidi",28),("Madaline",100),("Wyoming",39),("Lucian",5);
INSERT INTO `Ataque` (`nome`,`dano`) VALUES ("Tate",44),("Marvin",100),("Josiah",24),("Abbot",92),("Elvis",87),("Keane",86),("Urielle",53),("Quin",75),("Helen",68),("Beatrice",89);
INSERT INTO `Ataque` (`nome`,`dano`) VALUES ("Chase",83),("Evangeline",30),("Fitzgerald",62),("Tate",67),("Xyla",23),("Vaughan",64),("Kenneth",84),("Kenyon",26),("Molly",100),("Jerry",59);

--RACA
INSERT INTO `Raca` (`nomeRaca`) VALUES ("Heard Island and Mcdonald Islands"),("Jersey"),("Togo"),("Jordan"),("Sierra Leone"),("Ecuador"),("China"),("Namibia"),("Algeria"),("Yemen");
INSERT INTO `Raca` (`nomeRaca`) VALUES ("Korea, North"),("Malaysia"),("Haiti"),("French Polynesia"),("Vanuatu"),("Belize"),("Macedonia"),("Greece"),("Vanuatu"),("Palau");
INSERT INTO `Raca` (`nomeRaca`) VALUES ("Qatar"),("Cayman Islands"),("Reunion"),("Argentina"),("Burundi"),("Iran"),("French Guiana"),("Djibouti"),("New Caledonia"),("Jordan");
INSERT INTO `Raca` (`nomeRaca`) VALUES ("Iran"),("Heard Island and Mcdonald Islands"),("Portugal"),("France"),("Guyana"),("Montenegro"),("Korea, South"),("Kuwait"),("Heard Island and Mcdonald Islands"),("Morocco");
INSERT INTO `Raca` (`nomeRaca`) VALUES ("Georgia"),("Indonesia"),("Virgin Islands, United States"),("South Africa"),("Netherlands"),("Saint Vincent and The Grenadines"),("Cape Verde"),("Tonga"),("Taiwan"),("Timor-Leste");
INSERT INTO `Raca` (`nomeRaca`) VALUES ("Poland"),("Kazakhstan"),("Malta"),("Lesotho"),("French Polynesia"),("Svalbard and Jan Mayen Islands"),("Austria"),("Aruba"),("Ghana"),("Togo");
INSERT INTO `Raca` (`nomeRaca`) VALUES ("Cayman Islands"),("Kuwait"),("Barbados"),("Belize"),("Equatorial Guinea"),("Saint Kitts and Nevis"),("Mexico"),("United States"),("Micronesia"),("Lebanon");
INSERT INTO `Raca` (`nomeRaca`) VALUES ("Uzbekistan"),("Bahrain"),("Tanzania"),("India"),("Mauritius"),("Jamaica"),("Panama"),("Virgin Islands, British"),("Madagascar"),("Saint Lucia");
INSERT INTO `Raca` (`nomeRaca`) VALUES ("Grenada"),("Belgium"),("Mozambique"),("Macedonia"),("New Caledonia"),("Mauritius"),("Barbados"),("Tokelau"),("Macao"),("Georgia");
INSERT INTO `Raca` (`nomeRaca`) VALUES ("Belarus"),("Gibraltar"),("Bonaire, Sint Eustatius and Saba"),("Comoros"),("France"),("Wallis and Futuna"),("Djibouti"),("Niger"),("Rwanda"),("Vanuatu");

--HABILIDADE
INSERT INTO `Habilidade` (`tipoHabilidade`) VALUES ("Rhoncus Corp."),("Rhoncus Id Consulting"),("Eget Metus Industries"),("Tempus Eu Ligula Corporation"),("Felis Consulting"),("Velit Eget Incorporated"),("Penatibus Et Corp."),("Orci Incorporated"),("Odio Auctor Vitae PC"),("Tincidunt Congue Limited");
INSERT INTO `Habilidade` (`tipoHabilidade`) VALUES ("Dictum Eleifend Nunc Corporation"),("Tempor PC"),("Egestas Associates"),("Fermentum Convallis Ligula Corp."),("Neque Nullam Ltd"),("Enim Consulting"),("Sed Inc."),("Nibh Institute"),("Risus Quisque Ltd"),("Mauris Blandit Company");
INSERT INTO `Habilidade` (`tipoHabilidade`) VALUES ("Purus Ac Incorporated"),("Faucibus Morbi Vehicula LLP"),("Odio Tristique Corp."),("Dolor Donec Fringilla Incorporated"),("Tincidunt Donec LLP"),("Risus Incorporated"),("Feugiat Consulting"),("Nullam Scelerisque Neque Limited"),("In Company"),("Placerat Limited");
INSERT INTO `Habilidade` (`tipoHabilidade`) VALUES ("Adipiscing LLP"),("Interdum Feugiat PC"),("Duis Dignissim Limited"),("Dictum Cursus Nunc LLC"),("Est Consulting"),("Mi Ac Incorporated"),("Laoreet Corporation"),("Ac Risus Company"),("Placerat Augue Sed Foundation"),("Orci Tincidunt Adipiscing Corp.");
INSERT INTO `Habilidade` (`tipoHabilidade`) VALUES ("Donec Porttitor Inc."),("Sed Libero Associates"),("Ultricies Adipiscing Consulting"),("Quis Arcu PC"),("Fermentum Risus Inc."),("Luctus Vulputate Ltd"),("Quis Ltd"),("Dictum Magna Industries"),("Pede LLC"),("Mattis Corp.");
INSERT INTO `Habilidade` (`tipoHabilidade`) VALUES ("Ac Ipsum Phasellus Foundation"),("In Sodales Elit LLP"),("Arcu Corp."),("Sed Eget Lacus Corp."),("Molestie Orci Tincidunt Incorporated"),("Lorem LLP"),("Ullamcorper Inc."),("Mauris Ut Quam Corporation"),("Eu Ltd"),("Tincidunt Nunc Incorporated");
INSERT INTO `Habilidade` (`tipoHabilidade`) VALUES ("Ipsum Associates"),("Iaculis Quis Pede Consulting"),("Massa Mauris Corporation"),("Pede Cras Vulputate Consulting"),("Sem Limited"),("Amet Consectetuer Adipiscing Corporation"),("Lectus Incorporated"),("Quam Vel Limited"),("Rutrum Urna Institute"),("Ac LLP");
INSERT INTO `Habilidade` (`tipoHabilidade`) VALUES ("Lacus Inc."),("Nisl Consulting"),("Imperdiet Company"),("Diam Vel Arcu LLP"),("Eu Turpis Nulla Foundation"),("Lorem Donec Elementum Institute"),("Nostra LLC"),("Etiam Ltd"),("Nam Porttitor Scelerisque Consulting"),("Justo Nec Limited");
INSERT INTO `Habilidade` (`tipoHabilidade`) VALUES ("Elit Etiam Inc."),("Hendrerit Donec Porttitor Foundation"),("Velit Egestas Incorporated"),("Nunc Foundation"),("Elit Elit Fermentum Consulting"),("Ut Corp."),("Donec Dignissim Incorporated"),("Et Limited"),("In Lobortis Tellus Consulting"),("Et Ipsum LLC");
INSERT INTO `Habilidade` (`tipoHabilidade`) VALUES ("Enim Diam Vel Inc."),("Sit Amet Limited"),("Nisi Sem Semper Foundation"),("Dis Parturient Montes Corporation"),("Molestie Sed Foundation"),("Augue Ac Ipsum Industries"),("Magna Sed Dui Consulting"),("Egestas Company"),("Aliquam Incorporated"),("Egestas Ltd");

--E__Assoc__1_Aprende
INSERT INTO `E__Assoc__1_Aprende` (`valor`,`modificador`) VALUES (97,32),(88,4),(84,33),(42,52),(94,33),(30,29),(43,1),(86,45),(27,56),(6,40);
INSERT INTO `E__Assoc__1_Aprende` (`valor`,`modificador`) VALUES (15,78),(41,78),(27,36),(73,21),(18,41),(26,26),(83,81),(93,32),(26,21),(57,24);
INSERT INTO `E__Assoc__1_Aprende` (`valor`,`modificador`) VALUES (52,66),(63,63),(5,32),(19,94),(66,73),(56,84),(70,45),(88,57),(4,84),(15,37);
INSERT INTO `E__Assoc__1_Aprende` (`valor`,`modificador`) VALUES (31,24),(15,15),(66,37),(42,46),(41,11),(82,26),(86,65),(60,9),(18,7),(22,73);
INSERT INTO `E__Assoc__1_Aprende` (`valor`,`modificador`) VALUES (71,97),(100,22),(85,2),(56,8),(67,15),(52,99),(35,21),(57,25),(94,90),(96,76);
INSERT INTO `E__Assoc__1_Aprende` (`valor`,`modificador`) VALUES (72,93),(99,29),(67,6),(99,19),(49,1),(26,69),(32,22),(85,25),(83,18),(39,42);
INSERT INTO `E__Assoc__1_Aprende` (`valor`,`modificador`) VALUES (11,96),(74,65),(43,31),(66,2),(56,38),(85,36),(75,47),(42,6),(2,85),(80,13);
INSERT INTO `E__Assoc__1_Aprende` (`valor`,`modificador`) VALUES (45,96),(63,95),(61,31),(38,97),(80,80),(30,64),(32,13),(60,75),(92,14),(31,40);
INSERT INTO `E__Assoc__1_Aprende` (`valor`,`modificador`) VALUES (52,44),(79,43),(37,64),(19,55),(93,34),(84,67),(72,45),(28,77),(19,25),(26,42);
INSERT INTO `E__Assoc__1_Aprende` (`valor`,`modificador`) VALUES (44,70),(24,33),(23,40),(33,10),(28,58),(47,28),(69,5),(8,67),(1,84),(7,57);


--E__Assoc__2_Utiliza
INSERT INTO `E__Assoc__2_Utiliza` (`modificadorAtaque`) VALUES (24),(39),(72),(25),(79),(35),(5),(98),(27),(5);
INSERT INTO `E__Assoc__2_Utiliza` (`modificadorAtaque`) VALUES (49),(17),(67),(33),(64),(88),(40),(11),(68),(26);
INSERT INTO `E__Assoc__2_Utiliza` (`modificadorAtaque`) VALUES (80),(68),(93),(59),(8),(16),(33),(39),(71),(13);
INSERT INTO `E__Assoc__2_Utiliza` (`modificadorAtaque`) VALUES (36),(95),(2),(83),(11),(31),(10),(54),(47),(38);
INSERT INTO `E__Assoc__2_Utiliza` (`modificadorAtaque`) VALUES (40),(74),(65),(32),(24),(31),(91),(87),(8),(69);
INSERT INTO `E__Assoc__2_Utiliza` (`modificadorAtaque`) VALUES (71),(3),(49),(18),(91),(61),(75),(1),(23),(84);
INSERT INTO `E__Assoc__2_Utiliza` (`modificadorAtaque`) VALUES (84),(34),(84),(67),(75),(1),(99),(100),(51),(75);
INSERT INTO `E__Assoc__2_Utiliza` (`modificadorAtaque`) VALUES (91),(96),(1),(77),(30),(69),(3),(1),(49),(96);
INSERT INTO `E__Assoc__2_Utiliza` (`modificadorAtaque`) VALUES (52),(68),(96),(43),(46),(74),(8),(11),(92),(27);
INSERT INTO `E__Assoc__2_Utiliza` (`modificadorAtaque`) VALUES (39),(11),(41),(89),(21),(6),(72),(44),(28),(57);


-- --PERSONAGEM
INSERT INTO `Personagem` (`Nome`,`Nivel`,`Idade`,`Altura`,`Iniciativa`,`Velocidade`,`Pontos_de_ataque`) VALUES ("Bevis",10,51,138,10,5,2),("Omar",7,34,103,4,4,2),("Asher",3,82,217,3,7,1),("Vladimir",8,73,43,3,2,1),("Thomas",5,34,4,2,1,3),("Boris",1,68,54,4,9,9),("Cullen",2,19,118,3,8,2),("Asher",9,65,203,2,2,3),("Nasim",10,4,113,1,4,8),("Demetrius",10,30,123,3,5,5);
INSERT INTO `Personagem` (`Nome`,`Nivel`,`Idade`,`Altura`,`Iniciativa`,`Velocidade`,`Pontos_de_ataque`) VALUES ("Porter",9,71,223,8,1,9),("Cairo",3,89,65,1,3,8),("Martin",1,98,173,6,10,9),("Jordan",10,83,12,1,10,7),("Porter",1,18,195,6,7,7),("Ian",8,22,183,9,8,4),("Carter",3,4,213,2,2,10),("Nehru",3,1,199,9,2,5),("Brendan",6,100,228,4,3,6),("Macaulay",10,19,138,6,4,10);
INSERT INTO `Personagem` (`Nome`,`Nivel`,`Idade`,`Altura`,`Iniciativa`,`Velocidade`,`Pontos_de_ataque`) VALUES ("August",4,43,151,8,1,5),("Merritt",7,85,204,8,10,7),("Carl",9,56,24,8,6,3),("Xanthus",1,6,7,10,9,7),("Noble",9,68,169,3,2,10),("Hyatt",7,61,99,3,6,2),("Mufutau",6,55,119,2,3,4),("Colton",3,23,16,9,5,7),("Ashton",10,14,176,8,10,2),("Ezra",6,6,155,5,9,10);
INSERT INTO `Personagem` (`Nome`,`Nivel`,`Idade`,`Altura`,`Iniciativa`,`Velocidade`,`Pontos_de_ataque`) VALUES ("Hilel",6,66,46,2,5,4),("Adrian",9,82,15,8,9,9),("Ira",10,100,134,8,6,8),("Griffith",4,20,16,8,4,7),("Raja",7,98,242,7,8,2),("Hamish",4,10,113,3,7,3),("Kuame",9,98,121,10,6,10),("Samson",3,29,74,2,10,8),("Armando",1,61,45,10,7,8),("Timon",6,88,73,6,6,3);
INSERT INTO `Personagem` (`Nome`,`Nivel`,`Idade`,`Altura`,`Iniciativa`,`Velocidade`,`Pontos_de_ataque`) VALUES ("Cain",10,50,75,7,7,6),("Sean",1,34,230,5,9,1),("Valentine",3,49,160,1,6,3),("Kane",10,96,205,8,10,8),("Isaiah",4,84,133,8,10,6),("Ira",7,47,62,1,1,6),("Raja",10,48,4,9,10,5),("Jerry",1,46,19,5,3,1),("Ferris",10,29,31,7,8,7),("Evan",7,52,152,3,2,3);
INSERT INTO `Personagem` (`Nome`,`Nivel`,`Idade`,`Altura`,`Iniciativa`,`Velocidade`,`Pontos_de_ataque`) VALUES ("Charles",2,78,84,1,10,2),("Cameron",5,86,41,1,8,9),("George",7,22,154,10,5,7),("Ian",3,41,145,10,6,6),("Justin",8,30,98,6,2,6),("Chadwick",9,69,214,3,8,1),("Perry",3,75,11,4,9,10),("Andrew",10,24,217,10,5,3),("Gavin",5,30,154,1,10,4),("Jonas",10,95,234,7,5,3);
INSERT INTO `Personagem` (`Nome`,`Nivel`,`Idade`,`Altura`,`Iniciativa`,`Velocidade`,`Pontos_de_ataque`) VALUES ("Grant",3,80,37,8,7,2),("Timon",10,84,120,8,9,2),("Beau",6,36,65,8,5,9),("Cody",5,83,205,4,7,3),("Tad",8,15,217,8,6,6),("Prescott",5,75,93,5,2,10),("Ryan",1,28,62,8,8,10),("Channing",4,74,204,9,1,1),("Oliver",4,59,66,2,1,2),("Raymond",8,89,125,4,7,2);
INSERT INTO `Personagem` (`Nome`,`Nivel`,`Idade`,`Altura`,`Iniciativa`,`Velocidade`,`Pontos_de_ataque`) VALUES ("Anthony",7,15,33,3,1,9),("Lee",10,57,234,10,5,10),("Ishmael",6,36,206,9,2,5),("Lyle",2,72,180,1,3,2),("Aladdin",7,78,78,4,9,10),("Carter",10,94,18,8,9,5),("Matthew",5,14,58,1,6,5),("William",6,19,157,7,3,4),("Marvin",9,51,106,2,9,2),("Abel",9,45,220,9,1,7);
INSERT INTO `Personagem` (`Nome`,`Nivel`,`Idade`,`Altura`,`Iniciativa`,`Velocidade`,`Pontos_de_ataque`) VALUES ("Jonah",9,13,102,9,8,3),("Aidan",2,15,234,10,5,6),("Fritz",10,26,46,1,8,9),("Clarke",5,40,147,6,3,3),("Amal",4,50,118,4,3,6),("Zahir",10,5,60,6,7,10),("Kieran",3,100,168,5,8,4),("Garth",4,67,40,1,6,5),("Isaiah",1,48,21,10,1,9),("Macon",3,64,37,7,3,10);
INSERT INTO `Personagem` (`Nome`,`Nivel`,`Idade`,`Altura`,`Iniciativa`,`Velocidade`,`Pontos_de_ataque`) VALUES ("Vladimir",10,99,76,3,10,5),("Lester",4,68,32,8,1,1),("Leroy",3,15,142,8,3,9),("Aaron",5,68,249,1,3,6),("Griffin",1,75,122,5,2,7),("Carson",5,67,34,9,4,6),("Fuller",10,14,110,7,7,2),("Cyrus",1,44,53,8,10,6),("Burton",4,32,183,6,5,4),("Quamar",2,14,178,1,5,5);